/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalonSlugRouteImport } from './routes/salon.$slug'
import { Route as NetworkingSlugRouteImport } from './routes/networking.$slug'
import { Route as MeRoleRouteImport } from './routes/me.role'
import { Route as MeSlugRouteImport } from './routes/me.$slug'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as AttendanceSessionIdRouteImport } from './routes/attendance.$sessionId'
import { Route as AgendaSlugRouteImport } from './routes/agenda.$slug'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSecurityAuditRouteImport } from './routes/_authenticated/security-audit'
import { Route as AuthenticatedPollsRouteImport } from './routes/_authenticated/polls'
import { Route as AuthenticatedParticipantsRouteImport } from './routes/_authenticated/participants'
import { Route as AuthenticatedOrgRouteImport } from './routes/_authenticated/org'
import { Route as AuthenticatedExportsRouteImport } from './routes/_authenticated/exports'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCheckinRouteImport } from './routes/_authenticated/checkin'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ESlugReseauRouteImport } from './routes/e.$slug/reseau'
import { Route as ESlugProfilRouteImport } from './routes/e.$slug/profil'
import { Route as ESlugMessagesRouteImport } from './routes/e.$slug/messages'
import { Route as ESlugAnnoncesRouteImport } from './routes/e.$slug/annonces'
import { Route as ESlugAgendaRouteImport } from './routes/e.$slug/agenda'
import { Route as AuthenticatedStaffParticipantsRouteImport } from './routes/_authenticated/staff/participants'
import { Route as AuthenticatedStaffCheckinRouteImport } from './routes/_authenticated/staff/checkin'
import { Route as AuthenticatedStaffAnnouncementsRouteImport } from './routes/_authenticated/staff/announcements'
import { Route as AuthenticatedOrgParticipantsRouteImport } from './routes/_authenticated/org/participants'
import { Route as AuthenticatedOrgExportsRouteImport } from './routes/_authenticated/org/exports'
import { Route as AuthenticatedOrgEventsRouteImport } from './routes/_authenticated/org/events'
import { Route as AuthenticatedOrgCommunicationRouteImport } from './routes/_authenticated/org/communication'
import { Route as AuthenticatedOrgCockpitRouteImport } from './routes/_authenticated/org/cockpit'
import { Route as AuthenticatedEventsNewRouteImport } from './routes/_authenticated/events.new'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSetupRouteImport } from './routes/_authenticated/admin.setup'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin/security'
import { Route as AuthenticatedAdminOverviewRouteImport } from './routes/_authenticated/admin/overview'
import { Route as AuthenticatedAdminBootstrapRouteImport } from './routes/_authenticated/admin/bootstrap'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as ApiPublicAuthTokenRouteImport } from './routes/api/public/auth/token'
import { Route as ApiPublicAuthRecoverRouteImport } from './routes/api/public/auth/recover'
import { Route as AuthenticatedOrgEventsNewRouteImport } from './routes/_authenticated/org/events/new'
import { Route as AuthenticatedEventsIdSessionsRouteImport } from './routes/_authenticated/events.$id.sessions'
import { Route as AuthenticatedEventsIdRegistrationsRouteImport } from './routes/_authenticated/events.$id.registrations'
import { Route as AuthenticatedEventsIdEditRouteImport } from './routes/_authenticated/events.$id.edit'
import { Route as AuthenticatedOrgEventsIdSessionsRouteImport } from './routes/_authenticated/org/events.$id.sessions'
import { Route as AuthenticatedOrgEventsIdEditRouteImport } from './routes/_authenticated/org/events.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonSlugRoute = SalonSlugRouteImport.update({
  id: '/salon/$slug',
  path: '/salon/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkingSlugRoute = NetworkingSlugRouteImport.update({
  id: '/networking/$slug',
  path: '/networking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoleRoute = MeRoleRouteImport.update({
  id: '/me/role',
  path: '/me/role',
  getParentRoute: () => rootRouteImport,
} as any)
const MeSlugRoute = MeSlugRouteImport.update({
  id: '/me/$slug',
  path: '/me/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceSessionIdRoute = AttendanceSessionIdRouteImport.update({
  id: '/attendance/$sessionId',
  path: '/attendance/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaSlugRoute = AgendaSlugRouteImport.update({
  id: '/agenda/$slug',
  path: '/agenda/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityAuditRoute =
  AuthenticatedSecurityAuditRouteImport.update({
    id: '/security-audit',
    path: '/security-audit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPollsRoute = AuthenticatedPollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParticipantsRoute =
  AuthenticatedParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgRoute = AuthenticatedOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExportsRoute = AuthenticatedExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckinRoute = AuthenticatedCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ESlugReseauRoute = ESlugReseauRouteImport.update({
  id: '/reseau',
  path: '/reseau',
  getParentRoute: () => ESlugRoute,
} as any)
const ESlugProfilRoute = ESlugProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => ESlugRoute,
} as any)
const ESlugMessagesRoute = ESlugMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ESlugRoute,
} as any)
const ESlugAnnoncesRoute = ESlugAnnoncesRouteImport.update({
  id: '/annonces',
  path: '/annonces',
  getParentRoute: () => ESlugRoute,
} as any)
const ESlugAgendaRoute = ESlugAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ESlugRoute,
} as any)
const AuthenticatedStaffParticipantsRoute =
  AuthenticatedStaffParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffCheckinRoute =
  AuthenticatedStaffCheckinRouteImport.update({
    id: '/checkin',
    path: '/checkin',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffAnnouncementsRoute =
  AuthenticatedStaffAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedOrgParticipantsRoute =
  AuthenticatedOrgParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AuthenticatedOrgRoute,
  } as any)
const AuthenticatedOrgExportsRoute = AuthenticatedOrgExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AuthenticatedOrgRoute,
} as any)
const AuthenticatedOrgEventsRoute = AuthenticatedOrgEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedOrgRoute,
} as any)
const AuthenticatedOrgCommunicationRoute =
  AuthenticatedOrgCommunicationRouteImport.update({
    id: '/communication',
    path: '/communication',
    getParentRoute: () => AuthenticatedOrgRoute,
  } as any)
const AuthenticatedOrgCockpitRoute = AuthenticatedOrgCockpitRouteImport.update({
  id: '/cockpit',
  path: '/cockpit',
  getParentRoute: () => AuthenticatedOrgRoute,
} as any)
const AuthenticatedEventsNewRoute = AuthenticatedEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedEventsRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSetupRoute = AuthenticatedAdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOverviewRoute =
  AuthenticatedAdminOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBootstrapRoute =
  AuthenticatedAdminBootstrapRouteImport.update({
    id: '/bootstrap',
    path: '/bootstrap',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicAuthTokenRoute = ApiPublicAuthTokenRouteImport.update({
  id: '/api/public/auth/token',
  path: '/api/public/auth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthRecoverRoute = ApiPublicAuthRecoverRouteImport.update({
  id: '/api/public/auth/recover',
  path: '/api/public/auth/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgEventsNewRoute =
  AuthenticatedOrgEventsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedOrgEventsRoute,
  } as any)
const AuthenticatedEventsIdSessionsRoute =
  AuthenticatedEventsIdSessionsRouteImport.update({
    id: '/$id/sessions',
    path: '/$id/sessions',
    getParentRoute: () => AuthenticatedEventsRoute,
  } as any)
const AuthenticatedEventsIdRegistrationsRoute =
  AuthenticatedEventsIdRegistrationsRouteImport.update({
    id: '/$id/registrations',
    path: '/$id/registrations',
    getParentRoute: () => AuthenticatedEventsRoute,
  } as any)
const AuthenticatedEventsIdEditRoute =
  AuthenticatedEventsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedEventsRoute,
  } as any)
const AuthenticatedOrgEventsIdSessionsRoute =
  AuthenticatedOrgEventsIdSessionsRouteImport.update({
    id: '/$id/sessions',
    path: '/$id/sessions',
    getParentRoute: () => AuthenticatedOrgEventsRoute,
  } as any)
const AuthenticatedOrgEventsIdEditRoute =
  AuthenticatedOrgEventsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedOrgEventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRouteWithChildren
  '/exports': typeof AuthenticatedExportsRoute
  '/org': typeof AuthenticatedOrgRouteWithChildren
  '/participants': typeof AuthenticatedParticipantsRoute
  '/polls': typeof AuthenticatedPollsRoute
  '/security-audit': typeof AuthenticatedSecurityAuditRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/agenda/$slug': typeof AgendaSlugRoute
  '/attendance/$sessionId': typeof AttendanceSessionIdRoute
  '/e/$slug': typeof ESlugRouteWithChildren
  '/me/$slug': typeof MeSlugRoute
  '/me/role': typeof MeRoleRoute
  '/networking/$slug': typeof NetworkingSlugRoute
  '/salon/$slug': typeof SalonSlugRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bootstrap': typeof AuthenticatedAdminBootstrapRoute
  '/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/org/cockpit': typeof AuthenticatedOrgCockpitRoute
  '/org/communication': typeof AuthenticatedOrgCommunicationRoute
  '/org/events': typeof AuthenticatedOrgEventsRouteWithChildren
  '/org/exports': typeof AuthenticatedOrgExportsRoute
  '/org/participants': typeof AuthenticatedOrgParticipantsRoute
  '/staff/announcements': typeof AuthenticatedStaffAnnouncementsRoute
  '/staff/checkin': typeof AuthenticatedStaffCheckinRoute
  '/staff/participants': typeof AuthenticatedStaffParticipantsRoute
  '/e/$slug/agenda': typeof ESlugAgendaRoute
  '/e/$slug/annonces': typeof ESlugAnnoncesRoute
  '/e/$slug/messages': typeof ESlugMessagesRoute
  '/e/$slug/profil': typeof ESlugProfilRoute
  '/e/$slug/reseau': typeof ESlugReseauRoute
  '/events/$id/edit': typeof AuthenticatedEventsIdEditRoute
  '/events/$id/registrations': typeof AuthenticatedEventsIdRegistrationsRoute
  '/events/$id/sessions': typeof AuthenticatedEventsIdSessionsRoute
  '/org/events/new': typeof AuthenticatedOrgEventsNewRoute
  '/api/public/auth/recover': typeof ApiPublicAuthRecoverRoute
  '/api/public/auth/token': typeof ApiPublicAuthTokenRoute
  '/org/events/$id/edit': typeof AuthenticatedOrgEventsIdEditRoute
  '/org/events/$id/sessions': typeof AuthenticatedOrgEventsIdSessionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRouteWithChildren
  '/exports': typeof AuthenticatedExportsRoute
  '/org': typeof AuthenticatedOrgRouteWithChildren
  '/participants': typeof AuthenticatedParticipantsRoute
  '/polls': typeof AuthenticatedPollsRoute
  '/security-audit': typeof AuthenticatedSecurityAuditRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/agenda/$slug': typeof AgendaSlugRoute
  '/attendance/$sessionId': typeof AttendanceSessionIdRoute
  '/e/$slug': typeof ESlugRouteWithChildren
  '/me/$slug': typeof MeSlugRoute
  '/me/role': typeof MeRoleRoute
  '/networking/$slug': typeof NetworkingSlugRoute
  '/salon/$slug': typeof SalonSlugRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bootstrap': typeof AuthenticatedAdminBootstrapRoute
  '/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/org/cockpit': typeof AuthenticatedOrgCockpitRoute
  '/org/communication': typeof AuthenticatedOrgCommunicationRoute
  '/org/events': typeof AuthenticatedOrgEventsRouteWithChildren
  '/org/exports': typeof AuthenticatedOrgExportsRoute
  '/org/participants': typeof AuthenticatedOrgParticipantsRoute
  '/staff/announcements': typeof AuthenticatedStaffAnnouncementsRoute
  '/staff/checkin': typeof AuthenticatedStaffCheckinRoute
  '/staff/participants': typeof AuthenticatedStaffParticipantsRoute
  '/e/$slug/agenda': typeof ESlugAgendaRoute
  '/e/$slug/annonces': typeof ESlugAnnoncesRoute
  '/e/$slug/messages': typeof ESlugMessagesRoute
  '/e/$slug/profil': typeof ESlugProfilRoute
  '/e/$slug/reseau': typeof ESlugReseauRoute
  '/events/$id/edit': typeof AuthenticatedEventsIdEditRoute
  '/events/$id/registrations': typeof AuthenticatedEventsIdRegistrationsRoute
  '/events/$id/sessions': typeof AuthenticatedEventsIdSessionsRoute
  '/org/events/new': typeof AuthenticatedOrgEventsNewRoute
  '/api/public/auth/recover': typeof ApiPublicAuthRecoverRoute
  '/api/public/auth/token': typeof ApiPublicAuthTokenRoute
  '/org/events/$id/edit': typeof AuthenticatedOrgEventsIdEditRoute
  '/org/events/$id/sessions': typeof AuthenticatedOrgEventsIdSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/checkin': typeof AuthenticatedCheckinRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/events': typeof AuthenticatedEventsRouteWithChildren
  '/_authenticated/exports': typeof AuthenticatedExportsRoute
  '/_authenticated/org': typeof AuthenticatedOrgRouteWithChildren
  '/_authenticated/participants': typeof AuthenticatedParticipantsRoute
  '/_authenticated/polls': typeof AuthenticatedPollsRoute
  '/_authenticated/security-audit': typeof AuthenticatedSecurityAuditRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/agenda/$slug': typeof AgendaSlugRoute
  '/attendance/$sessionId': typeof AttendanceSessionIdRoute
  '/e/$slug': typeof ESlugRouteWithChildren
  '/me/$slug': typeof MeSlugRoute
  '/me/role': typeof MeRoleRoute
  '/networking/$slug': typeof NetworkingSlugRoute
  '/salon/$slug': typeof SalonSlugRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/bootstrap': typeof AuthenticatedAdminBootstrapRoute
  '/_authenticated/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/events/new': typeof AuthenticatedEventsNewRoute
  '/_authenticated/org/cockpit': typeof AuthenticatedOrgCockpitRoute
  '/_authenticated/org/communication': typeof AuthenticatedOrgCommunicationRoute
  '/_authenticated/org/events': typeof AuthenticatedOrgEventsRouteWithChildren
  '/_authenticated/org/exports': typeof AuthenticatedOrgExportsRoute
  '/_authenticated/org/participants': typeof AuthenticatedOrgParticipantsRoute
  '/_authenticated/staff/announcements': typeof AuthenticatedStaffAnnouncementsRoute
  '/_authenticated/staff/checkin': typeof AuthenticatedStaffCheckinRoute
  '/_authenticated/staff/participants': typeof AuthenticatedStaffParticipantsRoute
  '/e/$slug/agenda': typeof ESlugAgendaRoute
  '/e/$slug/annonces': typeof ESlugAnnoncesRoute
  '/e/$slug/messages': typeof ESlugMessagesRoute
  '/e/$slug/profil': typeof ESlugProfilRoute
  '/e/$slug/reseau': typeof ESlugReseauRoute
  '/_authenticated/events/$id/edit': typeof AuthenticatedEventsIdEditRoute
  '/_authenticated/events/$id/registrations': typeof AuthenticatedEventsIdRegistrationsRoute
  '/_authenticated/events/$id/sessions': typeof AuthenticatedEventsIdSessionsRoute
  '/_authenticated/org/events/new': typeof AuthenticatedOrgEventsNewRoute
  '/api/public/auth/recover': typeof ApiPublicAuthRecoverRoute
  '/api/public/auth/token': typeof ApiPublicAuthTokenRoute
  '/_authenticated/org/events/$id/edit': typeof AuthenticatedOrgEventsIdEditRoute
  '/_authenticated/org/events/$id/sessions': typeof AuthenticatedOrgEventsIdSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/announcements'
    | '/checkin'
    | '/dashboard'
    | '/events'
    | '/exports'
    | '/org'
    | '/participants'
    | '/polls'
    | '/security-audit'
    | '/staff'
    | '/agenda/$slug'
    | '/attendance/$sessionId'
    | '/e/$slug'
    | '/me/$slug'
    | '/me/role'
    | '/networking/$slug'
    | '/salon/$slug'
    | '/admin/audit'
    | '/admin/bootstrap'
    | '/admin/overview'
    | '/admin/security'
    | '/admin/setup'
    | '/admin/users'
    | '/events/new'
    | '/org/cockpit'
    | '/org/communication'
    | '/org/events'
    | '/org/exports'
    | '/org/participants'
    | '/staff/announcements'
    | '/staff/checkin'
    | '/staff/participants'
    | '/e/$slug/agenda'
    | '/e/$slug/annonces'
    | '/e/$slug/messages'
    | '/e/$slug/profil'
    | '/e/$slug/reseau'
    | '/events/$id/edit'
    | '/events/$id/registrations'
    | '/events/$id/sessions'
    | '/org/events/new'
    | '/api/public/auth/recover'
    | '/api/public/auth/token'
    | '/org/events/$id/edit'
    | '/org/events/$id/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/announcements'
    | '/checkin'
    | '/dashboard'
    | '/events'
    | '/exports'
    | '/org'
    | '/participants'
    | '/polls'
    | '/security-audit'
    | '/staff'
    | '/agenda/$slug'
    | '/attendance/$sessionId'
    | '/e/$slug'
    | '/me/$slug'
    | '/me/role'
    | '/networking/$slug'
    | '/salon/$slug'
    | '/admin/audit'
    | '/admin/bootstrap'
    | '/admin/overview'
    | '/admin/security'
    | '/admin/setup'
    | '/admin/users'
    | '/events/new'
    | '/org/cockpit'
    | '/org/communication'
    | '/org/events'
    | '/org/exports'
    | '/org/participants'
    | '/staff/announcements'
    | '/staff/checkin'
    | '/staff/participants'
    | '/e/$slug/agenda'
    | '/e/$slug/annonces'
    | '/e/$slug/messages'
    | '/e/$slug/profil'
    | '/e/$slug/reseau'
    | '/events/$id/edit'
    | '/events/$id/registrations'
    | '/events/$id/sessions'
    | '/org/events/new'
    | '/api/public/auth/recover'
    | '/api/public/auth/token'
    | '/org/events/$id/edit'
    | '/org/events/$id/sessions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forbidden'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/announcements'
    | '/_authenticated/checkin'
    | '/_authenticated/dashboard'
    | '/_authenticated/events'
    | '/_authenticated/exports'
    | '/_authenticated/org'
    | '/_authenticated/participants'
    | '/_authenticated/polls'
    | '/_authenticated/security-audit'
    | '/_authenticated/staff'
    | '/agenda/$slug'
    | '/attendance/$sessionId'
    | '/e/$slug'
    | '/me/$slug'
    | '/me/role'
    | '/networking/$slug'
    | '/salon/$slug'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/bootstrap'
    | '/_authenticated/admin/overview'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/setup'
    | '/_authenticated/admin/users'
    | '/_authenticated/events/new'
    | '/_authenticated/org/cockpit'
    | '/_authenticated/org/communication'
    | '/_authenticated/org/events'
    | '/_authenticated/org/exports'
    | '/_authenticated/org/participants'
    | '/_authenticated/staff/announcements'
    | '/_authenticated/staff/checkin'
    | '/_authenticated/staff/participants'
    | '/e/$slug/agenda'
    | '/e/$slug/annonces'
    | '/e/$slug/messages'
    | '/e/$slug/profil'
    | '/e/$slug/reseau'
    | '/_authenticated/events/$id/edit'
    | '/_authenticated/events/$id/registrations'
    | '/_authenticated/events/$id/sessions'
    | '/_authenticated/org/events/new'
    | '/api/public/auth/recover'
    | '/api/public/auth/token'
    | '/_authenticated/org/events/$id/edit'
    | '/_authenticated/org/events/$id/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AgendaSlugRoute: typeof AgendaSlugRoute
  AttendanceSessionIdRoute: typeof AttendanceSessionIdRoute
  ESlugRoute: typeof ESlugRouteWithChildren
  MeSlugRoute: typeof MeSlugRoute
  MeRoleRoute: typeof MeRoleRoute
  NetworkingSlugRoute: typeof NetworkingSlugRoute
  SalonSlugRoute: typeof SalonSlugRoute
  ApiPublicAuthRecoverRoute: typeof ApiPublicAuthRecoverRoute
  ApiPublicAuthTokenRoute: typeof ApiPublicAuthTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon/$slug': {
      id: '/salon/$slug'
      path: '/salon/$slug'
      fullPath: '/salon/$slug'
      preLoaderRoute: typeof SalonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networking/$slug': {
      id: '/networking/$slug'
      path: '/networking/$slug'
      fullPath: '/networking/$slug'
      preLoaderRoute: typeof NetworkingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/role': {
      id: '/me/role'
      path: '/me/role'
      fullPath: '/me/role'
      preLoaderRoute: typeof MeRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/$slug': {
      id: '/me/$slug'
      path: '/me/$slug'
      fullPath: '/me/$slug'
      preLoaderRoute: typeof MeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/$sessionId': {
      id: '/attendance/$sessionId'
      path: '/attendance/$sessionId'
      fullPath: '/attendance/$sessionId'
      preLoaderRoute: typeof AttendanceSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/$slug': {
      id: '/agenda/$slug'
      path: '/agenda/$slug'
      fullPath: '/agenda/$slug'
      preLoaderRoute: typeof AgendaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security-audit': {
      id: '/_authenticated/security-audit'
      path: '/security-audit'
      fullPath: '/security-audit'
      preLoaderRoute: typeof AuthenticatedSecurityAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/polls': {
      id: '/_authenticated/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof AuthenticatedPollsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/participants': {
      id: '/_authenticated/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof AuthenticatedParticipantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/org': {
      id: '/_authenticated/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof AuthenticatedOrgRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exports': {
      id: '/_authenticated/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AuthenticatedExportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkin': {
      id: '/_authenticated/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AuthenticatedCheckinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/e/$slug/reseau': {
      id: '/e/$slug/reseau'
      path: '/reseau'
      fullPath: '/e/$slug/reseau'
      preLoaderRoute: typeof ESlugReseauRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/e/$slug/profil': {
      id: '/e/$slug/profil'
      path: '/profil'
      fullPath: '/e/$slug/profil'
      preLoaderRoute: typeof ESlugProfilRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/e/$slug/messages': {
      id: '/e/$slug/messages'
      path: '/messages'
      fullPath: '/e/$slug/messages'
      preLoaderRoute: typeof ESlugMessagesRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/e/$slug/annonces': {
      id: '/e/$slug/annonces'
      path: '/annonces'
      fullPath: '/e/$slug/annonces'
      preLoaderRoute: typeof ESlugAnnoncesRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/e/$slug/agenda': {
      id: '/e/$slug/agenda'
      path: '/agenda'
      fullPath: '/e/$slug/agenda'
      preLoaderRoute: typeof ESlugAgendaRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/_authenticated/staff/participants': {
      id: '/_authenticated/staff/participants'
      path: '/participants'
      fullPath: '/staff/participants'
      preLoaderRoute: typeof AuthenticatedStaffParticipantsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/checkin': {
      id: '/_authenticated/staff/checkin'
      path: '/checkin'
      fullPath: '/staff/checkin'
      preLoaderRoute: typeof AuthenticatedStaffCheckinRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/announcements': {
      id: '/_authenticated/staff/announcements'
      path: '/announcements'
      fullPath: '/staff/announcements'
      preLoaderRoute: typeof AuthenticatedStaffAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/org/participants': {
      id: '/_authenticated/org/participants'
      path: '/participants'
      fullPath: '/org/participants'
      preLoaderRoute: typeof AuthenticatedOrgParticipantsRouteImport
      parentRoute: typeof AuthenticatedOrgRoute
    }
    '/_authenticated/org/exports': {
      id: '/_authenticated/org/exports'
      path: '/exports'
      fullPath: '/org/exports'
      preLoaderRoute: typeof AuthenticatedOrgExportsRouteImport
      parentRoute: typeof AuthenticatedOrgRoute
    }
    '/_authenticated/org/events': {
      id: '/_authenticated/org/events'
      path: '/events'
      fullPath: '/org/events'
      preLoaderRoute: typeof AuthenticatedOrgEventsRouteImport
      parentRoute: typeof AuthenticatedOrgRoute
    }
    '/_authenticated/org/communication': {
      id: '/_authenticated/org/communication'
      path: '/communication'
      fullPath: '/org/communication'
      preLoaderRoute: typeof AuthenticatedOrgCommunicationRouteImport
      parentRoute: typeof AuthenticatedOrgRoute
    }
    '/_authenticated/org/cockpit': {
      id: '/_authenticated/org/cockpit'
      path: '/cockpit'
      fullPath: '/org/cockpit'
      preLoaderRoute: typeof AuthenticatedOrgCockpitRouteImport
      parentRoute: typeof AuthenticatedOrgRoute
    }
    '/_authenticated/events/new': {
      id: '/_authenticated/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthenticatedEventsNewRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/setup': {
      id: '/_authenticated/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AuthenticatedAdminSetupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/overview': {
      id: '/_authenticated/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AuthenticatedAdminOverviewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bootstrap': {
      id: '/_authenticated/admin/bootstrap'
      path: '/bootstrap'
      fullPath: '/admin/bootstrap'
      preLoaderRoute: typeof AuthenticatedAdminBootstrapRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/auth/token': {
      id: '/api/public/auth/token'
      path: '/api/public/auth/token'
      fullPath: '/api/public/auth/token'
      preLoaderRoute: typeof ApiPublicAuthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/recover': {
      id: '/api/public/auth/recover'
      path: '/api/public/auth/recover'
      fullPath: '/api/public/auth/recover'
      preLoaderRoute: typeof ApiPublicAuthRecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/org/events/new': {
      id: '/_authenticated/org/events/new'
      path: '/new'
      fullPath: '/org/events/new'
      preLoaderRoute: typeof AuthenticatedOrgEventsNewRouteImport
      parentRoute: typeof AuthenticatedOrgEventsRoute
    }
    '/_authenticated/events/$id/sessions': {
      id: '/_authenticated/events/$id/sessions'
      path: '/$id/sessions'
      fullPath: '/events/$id/sessions'
      preLoaderRoute: typeof AuthenticatedEventsIdSessionsRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/events/$id/registrations': {
      id: '/_authenticated/events/$id/registrations'
      path: '/$id/registrations'
      fullPath: '/events/$id/registrations'
      preLoaderRoute: typeof AuthenticatedEventsIdRegistrationsRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/events/$id/edit': {
      id: '/_authenticated/events/$id/edit'
      path: '/$id/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof AuthenticatedEventsIdEditRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/org/events/$id/sessions': {
      id: '/_authenticated/org/events/$id/sessions'
      path: '/$id/sessions'
      fullPath: '/org/events/$id/sessions'
      preLoaderRoute: typeof AuthenticatedOrgEventsIdSessionsRouteImport
      parentRoute: typeof AuthenticatedOrgEventsRoute
    }
    '/_authenticated/org/events/$id/edit': {
      id: '/_authenticated/org/events/$id/edit'
      path: '/$id/edit'
      fullPath: '/org/events/$id/edit'
      preLoaderRoute: typeof AuthenticatedOrgEventsIdEditRouteImport
      parentRoute: typeof AuthenticatedOrgEventsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBootstrapRoute: typeof AuthenticatedAdminBootstrapRoute
  AuthenticatedAdminOverviewRoute: typeof AuthenticatedAdminOverviewRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSetupRoute: typeof AuthenticatedAdminSetupRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBootstrapRoute: AuthenticatedAdminBootstrapRoute,
  AuthenticatedAdminOverviewRoute: AuthenticatedAdminOverviewRoute,
  AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
  AuthenticatedAdminSetupRoute: AuthenticatedAdminSetupRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedEventsRouteChildren {
  AuthenticatedEventsNewRoute: typeof AuthenticatedEventsNewRoute
  AuthenticatedEventsIdEditRoute: typeof AuthenticatedEventsIdEditRoute
  AuthenticatedEventsIdRegistrationsRoute: typeof AuthenticatedEventsIdRegistrationsRoute
  AuthenticatedEventsIdSessionsRoute: typeof AuthenticatedEventsIdSessionsRoute
}

const AuthenticatedEventsRouteChildren: AuthenticatedEventsRouteChildren = {
  AuthenticatedEventsNewRoute: AuthenticatedEventsNewRoute,
  AuthenticatedEventsIdEditRoute: AuthenticatedEventsIdEditRoute,
  AuthenticatedEventsIdRegistrationsRoute:
    AuthenticatedEventsIdRegistrationsRoute,
  AuthenticatedEventsIdSessionsRoute: AuthenticatedEventsIdSessionsRoute,
}

const AuthenticatedEventsRouteWithChildren =
  AuthenticatedEventsRoute._addFileChildren(AuthenticatedEventsRouteChildren)

interface AuthenticatedOrgEventsRouteChildren {
  AuthenticatedOrgEventsNewRoute: typeof AuthenticatedOrgEventsNewRoute
  AuthenticatedOrgEventsIdEditRoute: typeof AuthenticatedOrgEventsIdEditRoute
  AuthenticatedOrgEventsIdSessionsRoute: typeof AuthenticatedOrgEventsIdSessionsRoute
}

const AuthenticatedOrgEventsRouteChildren: AuthenticatedOrgEventsRouteChildren =
  {
    AuthenticatedOrgEventsNewRoute: AuthenticatedOrgEventsNewRoute,
    AuthenticatedOrgEventsIdEditRoute: AuthenticatedOrgEventsIdEditRoute,
    AuthenticatedOrgEventsIdSessionsRoute:
      AuthenticatedOrgEventsIdSessionsRoute,
  }

const AuthenticatedOrgEventsRouteWithChildren =
  AuthenticatedOrgEventsRoute._addFileChildren(
    AuthenticatedOrgEventsRouteChildren,
  )

interface AuthenticatedOrgRouteChildren {
  AuthenticatedOrgCockpitRoute: typeof AuthenticatedOrgCockpitRoute
  AuthenticatedOrgCommunicationRoute: typeof AuthenticatedOrgCommunicationRoute
  AuthenticatedOrgEventsRoute: typeof AuthenticatedOrgEventsRouteWithChildren
  AuthenticatedOrgExportsRoute: typeof AuthenticatedOrgExportsRoute
  AuthenticatedOrgParticipantsRoute: typeof AuthenticatedOrgParticipantsRoute
}

const AuthenticatedOrgRouteChildren: AuthenticatedOrgRouteChildren = {
  AuthenticatedOrgCockpitRoute: AuthenticatedOrgCockpitRoute,
  AuthenticatedOrgCommunicationRoute: AuthenticatedOrgCommunicationRoute,
  AuthenticatedOrgEventsRoute: AuthenticatedOrgEventsRouteWithChildren,
  AuthenticatedOrgExportsRoute: AuthenticatedOrgExportsRoute,
  AuthenticatedOrgParticipantsRoute: AuthenticatedOrgParticipantsRoute,
}

const AuthenticatedOrgRouteWithChildren =
  AuthenticatedOrgRoute._addFileChildren(AuthenticatedOrgRouteChildren)

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffAnnouncementsRoute: typeof AuthenticatedStaffAnnouncementsRoute
  AuthenticatedStaffCheckinRoute: typeof AuthenticatedStaffCheckinRoute
  AuthenticatedStaffParticipantsRoute: typeof AuthenticatedStaffParticipantsRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffAnnouncementsRoute: AuthenticatedStaffAnnouncementsRoute,
  AuthenticatedStaffCheckinRoute: AuthenticatedStaffCheckinRoute,
  AuthenticatedStaffParticipantsRoute: AuthenticatedStaffParticipantsRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedCheckinRoute: typeof AuthenticatedCheckinRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRouteWithChildren
  AuthenticatedExportsRoute: typeof AuthenticatedExportsRoute
  AuthenticatedOrgRoute: typeof AuthenticatedOrgRouteWithChildren
  AuthenticatedParticipantsRoute: typeof AuthenticatedParticipantsRoute
  AuthenticatedPollsRoute: typeof AuthenticatedPollsRoute
  AuthenticatedSecurityAuditRoute: typeof AuthenticatedSecurityAuditRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedCheckinRoute: AuthenticatedCheckinRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRouteWithChildren,
  AuthenticatedExportsRoute: AuthenticatedExportsRoute,
  AuthenticatedOrgRoute: AuthenticatedOrgRouteWithChildren,
  AuthenticatedParticipantsRoute: AuthenticatedParticipantsRoute,
  AuthenticatedPollsRoute: AuthenticatedPollsRoute,
  AuthenticatedSecurityAuditRoute: AuthenticatedSecurityAuditRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ESlugRouteChildren {
  ESlugAgendaRoute: typeof ESlugAgendaRoute
  ESlugAnnoncesRoute: typeof ESlugAnnoncesRoute
  ESlugMessagesRoute: typeof ESlugMessagesRoute
  ESlugProfilRoute: typeof ESlugProfilRoute
  ESlugReseauRoute: typeof ESlugReseauRoute
}

const ESlugRouteChildren: ESlugRouteChildren = {
  ESlugAgendaRoute: ESlugAgendaRoute,
  ESlugAnnoncesRoute: ESlugAnnoncesRoute,
  ESlugMessagesRoute: ESlugMessagesRoute,
  ESlugProfilRoute: ESlugProfilRoute,
  ESlugReseauRoute: ESlugReseauRoute,
}

const ESlugRouteWithChildren = ESlugRoute._addFileChildren(ESlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AgendaSlugRoute: AgendaSlugRoute,
  AttendanceSessionIdRoute: AttendanceSessionIdRoute,
  ESlugRoute: ESlugRouteWithChildren,
  MeSlugRoute: MeSlugRoute,
  MeRoleRoute: MeRoleRoute,
  NetworkingSlugRoute: NetworkingSlugRoute,
  SalonSlugRoute: SalonSlugRoute,
  ApiPublicAuthRecoverRoute: ApiPublicAuthRecoverRoute,
  ApiPublicAuthTokenRoute: ApiPublicAuthTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
