/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RdvSlugRouteImport } from './routes/rdv.$slug'
import { Route as PollPollIdRouteImport } from './routes/poll.$pollId'
import { Route as NetworkingSlugRouteImport } from './routes/networking.$slug'
import { Route as MessagesSlugRouteImport } from './routes/messages.$slug'
import { Route as MeRoleRouteImport } from './routes/me.role'
import { Route as MatchmakingSlugRouteImport } from './routes/matchmaking.$slug'
import { Route as LiveSessionIdRouteImport } from './routes/live.$sessionId'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as AttendanceSessionIdRouteImport } from './routes/attendance.$sessionId'
import { Route as AnnoncesSlugRouteImport } from './routes/annonces.$slug'
import { Route as AgendaSlugRouteImport } from './routes/agenda.$slug'
import { Route as AuthenticatedSecurityAuditRouteImport } from './routes/_authenticated/security-audit'
import { Route as AuthenticatedPollsRouteImport } from './routes/_authenticated/polls'
import { Route as AuthenticatedParticipantsRouteImport } from './routes/_authenticated/participants'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCheckinRouteImport } from './routes/_authenticated/checkin'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedEventsNewRouteImport } from './routes/_authenticated/events.new'
import { Route as AuthenticatedAdminSetupRouteImport } from './routes/_authenticated/admin.setup'
import { Route as ApiPublicAuthTokenRouteImport } from './routes/api/public/auth/token'
import { Route as ApiPublicAuthRecoverRouteImport } from './routes/api/public/auth/recover'
import { Route as AuthenticatedEventsIdSessionsRouteImport } from './routes/_authenticated/events.$id.sessions'
import { Route as AuthenticatedEventsIdRegistrationsRouteImport } from './routes/_authenticated/events.$id.registrations'
import { Route as AuthenticatedEventsIdEditRouteImport } from './routes/_authenticated/events.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RdvSlugRoute = RdvSlugRouteImport.update({
  id: '/rdv/$slug',
  path: '/rdv/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PollPollIdRoute = PollPollIdRouteImport.update({
  id: '/poll/$pollId',
  path: '/poll/$pollId',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkingSlugRoute = NetworkingSlugRouteImport.update({
  id: '/networking/$slug',
  path: '/networking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesSlugRoute = MessagesSlugRouteImport.update({
  id: '/messages/$slug',
  path: '/messages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoleRoute = MeRoleRouteImport.update({
  id: '/me/role',
  path: '/me/role',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchmakingSlugRoute = MatchmakingSlugRouteImport.update({
  id: '/matchmaking/$slug',
  path: '/matchmaking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSessionIdRoute = LiveSessionIdRouteImport.update({
  id: '/live/$sessionId',
  path: '/live/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceSessionIdRoute = AttendanceSessionIdRouteImport.update({
  id: '/attendance/$sessionId',
  path: '/attendance/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesSlugRoute = AnnoncesSlugRouteImport.update({
  id: '/annonces/$slug',
  path: '/annonces/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaSlugRoute = AgendaSlugRouteImport.update({
  id: '/agenda/$slug',
  path: '/agenda/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSecurityAuditRoute =
  AuthenticatedSecurityAuditRouteImport.update({
    id: '/security-audit',
    path: '/security-audit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPollsRoute = AuthenticatedPollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParticipantsRoute =
  AuthenticatedParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckinRoute = AuthenticatedCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsNewRoute = AuthenticatedEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedEventsRoute,
} as any)
const AuthenticatedAdminSetupRoute = AuthenticatedAdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicAuthTokenRoute = ApiPublicAuthTokenRouteImport.update({
  id: '/api/public/auth/token',
  path: '/api/public/auth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthRecoverRoute = ApiPublicAuthRecoverRouteImport.update({
  id: '/api/public/auth/recover',
  path: '/api/public/auth/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEventsIdSessionsRoute =
  AuthenticatedEventsIdSessionsRouteImport.update({
    id: '/$id/sessions',
    path: '/$id/sessions',
    getParentRoute: () => AuthenticatedEventsRoute,
  } as any)
const AuthenticatedEventsIdRegistrationsRoute =
  AuthenticatedEventsIdRegistrationsRouteImport.update({
    id: '/$id/registrations',
    path: '/$id/registrations',
    getParentRoute: () => AuthenticatedEventsRoute,
  } as any)
const AuthenticatedEventsIdEditRoute =
  AuthenticatedEventsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedEventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRouteWithChildren
  '/participants': typeof AuthenticatedParticipantsRoute
  '/polls': typeof AuthenticatedPollsRoute
  '/security-audit': typeof AuthenticatedSecurityAuditRoute
  '/agenda/$slug': typeof AgendaSlugRoute
  '/annonces/$slug': typeof AnnoncesSlugRoute
  '/attendance/$sessionId': typeof AttendanceSessionIdRoute
  '/e/$slug': typeof ESlugRoute
  '/live/$sessionId': typeof LiveSessionIdRoute
  '/matchmaking/$slug': typeof MatchmakingSlugRoute
  '/me/role': typeof MeRoleRoute
  '/messages/$slug': typeof MessagesSlugRoute
  '/networking/$slug': typeof NetworkingSlugRoute
  '/poll/$pollId': typeof PollPollIdRoute
  '/rdv/$slug': typeof RdvSlugRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/events/$id/edit': typeof AuthenticatedEventsIdEditRoute
  '/events/$id/registrations': typeof AuthenticatedEventsIdRegistrationsRoute
  '/events/$id/sessions': typeof AuthenticatedEventsIdSessionsRoute
  '/api/public/auth/recover': typeof ApiPublicAuthRecoverRoute
  '/api/public/auth/token': typeof ApiPublicAuthTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRouteWithChildren
  '/participants': typeof AuthenticatedParticipantsRoute
  '/polls': typeof AuthenticatedPollsRoute
  '/security-audit': typeof AuthenticatedSecurityAuditRoute
  '/agenda/$slug': typeof AgendaSlugRoute
  '/annonces/$slug': typeof AnnoncesSlugRoute
  '/attendance/$sessionId': typeof AttendanceSessionIdRoute
  '/e/$slug': typeof ESlugRoute
  '/live/$sessionId': typeof LiveSessionIdRoute
  '/matchmaking/$slug': typeof MatchmakingSlugRoute
  '/me/role': typeof MeRoleRoute
  '/messages/$slug': typeof MessagesSlugRoute
  '/networking/$slug': typeof NetworkingSlugRoute
  '/poll/$pollId': typeof PollPollIdRoute
  '/rdv/$slug': typeof RdvSlugRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/events/$id/edit': typeof AuthenticatedEventsIdEditRoute
  '/events/$id/registrations': typeof AuthenticatedEventsIdRegistrationsRoute
  '/events/$id/sessions': typeof AuthenticatedEventsIdSessionsRoute
  '/api/public/auth/recover': typeof ApiPublicAuthRecoverRoute
  '/api/public/auth/token': typeof ApiPublicAuthTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/checkin': typeof AuthenticatedCheckinRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/events': typeof AuthenticatedEventsRouteWithChildren
  '/_authenticated/participants': typeof AuthenticatedParticipantsRoute
  '/_authenticated/polls': typeof AuthenticatedPollsRoute
  '/_authenticated/security-audit': typeof AuthenticatedSecurityAuditRoute
  '/agenda/$slug': typeof AgendaSlugRoute
  '/annonces/$slug': typeof AnnoncesSlugRoute
  '/attendance/$sessionId': typeof AttendanceSessionIdRoute
  '/e/$slug': typeof ESlugRoute
  '/live/$sessionId': typeof LiveSessionIdRoute
  '/matchmaking/$slug': typeof MatchmakingSlugRoute
  '/me/role': typeof MeRoleRoute
  '/messages/$slug': typeof MessagesSlugRoute
  '/networking/$slug': typeof NetworkingSlugRoute
  '/poll/$pollId': typeof PollPollIdRoute
  '/rdv/$slug': typeof RdvSlugRoute
  '/_authenticated/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/_authenticated/events/new': typeof AuthenticatedEventsNewRoute
  '/_authenticated/events/$id/edit': typeof AuthenticatedEventsIdEditRoute
  '/_authenticated/events/$id/registrations': typeof AuthenticatedEventsIdRegistrationsRoute
  '/_authenticated/events/$id/sessions': typeof AuthenticatedEventsIdSessionsRoute
  '/api/public/auth/recover': typeof ApiPublicAuthRecoverRoute
  '/api/public/auth/token': typeof ApiPublicAuthTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/reset-password'
    | '/signup'
    | '/announcements'
    | '/checkin'
    | '/dashboard'
    | '/events'
    | '/participants'
    | '/polls'
    | '/security-audit'
    | '/agenda/$slug'
    | '/annonces/$slug'
    | '/attendance/$sessionId'
    | '/e/$slug'
    | '/live/$sessionId'
    | '/matchmaking/$slug'
    | '/me/role'
    | '/messages/$slug'
    | '/networking/$slug'
    | '/poll/$pollId'
    | '/rdv/$slug'
    | '/admin/setup'
    | '/events/new'
    | '/events/$id/edit'
    | '/events/$id/registrations'
    | '/events/$id/sessions'
    | '/api/public/auth/recover'
    | '/api/public/auth/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/reset-password'
    | '/signup'
    | '/announcements'
    | '/checkin'
    | '/dashboard'
    | '/events'
    | '/participants'
    | '/polls'
    | '/security-audit'
    | '/agenda/$slug'
    | '/annonces/$slug'
    | '/attendance/$sessionId'
    | '/e/$slug'
    | '/live/$sessionId'
    | '/matchmaking/$slug'
    | '/me/role'
    | '/messages/$slug'
    | '/networking/$slug'
    | '/poll/$pollId'
    | '/rdv/$slug'
    | '/admin/setup'
    | '/events/new'
    | '/events/$id/edit'
    | '/events/$id/registrations'
    | '/events/$id/sessions'
    | '/api/public/auth/recover'
    | '/api/public/auth/token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forbidden'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/announcements'
    | '/_authenticated/checkin'
    | '/_authenticated/dashboard'
    | '/_authenticated/events'
    | '/_authenticated/participants'
    | '/_authenticated/polls'
    | '/_authenticated/security-audit'
    | '/agenda/$slug'
    | '/annonces/$slug'
    | '/attendance/$sessionId'
    | '/e/$slug'
    | '/live/$sessionId'
    | '/matchmaking/$slug'
    | '/me/role'
    | '/messages/$slug'
    | '/networking/$slug'
    | '/poll/$pollId'
    | '/rdv/$slug'
    | '/_authenticated/admin/setup'
    | '/_authenticated/events/new'
    | '/_authenticated/events/$id/edit'
    | '/_authenticated/events/$id/registrations'
    | '/_authenticated/events/$id/sessions'
    | '/api/public/auth/recover'
    | '/api/public/auth/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AgendaSlugRoute: typeof AgendaSlugRoute
  AnnoncesSlugRoute: typeof AnnoncesSlugRoute
  AttendanceSessionIdRoute: typeof AttendanceSessionIdRoute
  ESlugRoute: typeof ESlugRoute
  LiveSessionIdRoute: typeof LiveSessionIdRoute
  MatchmakingSlugRoute: typeof MatchmakingSlugRoute
  MeRoleRoute: typeof MeRoleRoute
  MessagesSlugRoute: typeof MessagesSlugRoute
  NetworkingSlugRoute: typeof NetworkingSlugRoute
  PollPollIdRoute: typeof PollPollIdRoute
  RdvSlugRoute: typeof RdvSlugRoute
  ApiPublicAuthRecoverRoute: typeof ApiPublicAuthRecoverRoute
  ApiPublicAuthTokenRoute: typeof ApiPublicAuthTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rdv/$slug': {
      id: '/rdv/$slug'
      path: '/rdv/$slug'
      fullPath: '/rdv/$slug'
      preLoaderRoute: typeof RdvSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/$pollId': {
      id: '/poll/$pollId'
      path: '/poll/$pollId'
      fullPath: '/poll/$pollId'
      preLoaderRoute: typeof PollPollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networking/$slug': {
      id: '/networking/$slug'
      path: '/networking/$slug'
      fullPath: '/networking/$slug'
      preLoaderRoute: typeof NetworkingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$slug': {
      id: '/messages/$slug'
      path: '/messages/$slug'
      fullPath: '/messages/$slug'
      preLoaderRoute: typeof MessagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/role': {
      id: '/me/role'
      path: '/me/role'
      fullPath: '/me/role'
      preLoaderRoute: typeof MeRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchmaking/$slug': {
      id: '/matchmaking/$slug'
      path: '/matchmaking/$slug'
      fullPath: '/matchmaking/$slug'
      preLoaderRoute: typeof MatchmakingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$sessionId': {
      id: '/live/$sessionId'
      path: '/live/$sessionId'
      fullPath: '/live/$sessionId'
      preLoaderRoute: typeof LiveSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/$sessionId': {
      id: '/attendance/$sessionId'
      path: '/attendance/$sessionId'
      fullPath: '/attendance/$sessionId'
      preLoaderRoute: typeof AttendanceSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces/$slug': {
      id: '/annonces/$slug'
      path: '/annonces/$slug'
      fullPath: '/annonces/$slug'
      preLoaderRoute: typeof AnnoncesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/$slug': {
      id: '/agenda/$slug'
      path: '/agenda/$slug'
      fullPath: '/agenda/$slug'
      preLoaderRoute: typeof AgendaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/security-audit': {
      id: '/_authenticated/security-audit'
      path: '/security-audit'
      fullPath: '/security-audit'
      preLoaderRoute: typeof AuthenticatedSecurityAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/polls': {
      id: '/_authenticated/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof AuthenticatedPollsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/participants': {
      id: '/_authenticated/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof AuthenticatedParticipantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkin': {
      id: '/_authenticated/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AuthenticatedCheckinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/new': {
      id: '/_authenticated/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthenticatedEventsNewRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/admin/setup': {
      id: '/_authenticated/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AuthenticatedAdminSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/auth/token': {
      id: '/api/public/auth/token'
      path: '/api/public/auth/token'
      fullPath: '/api/public/auth/token'
      preLoaderRoute: typeof ApiPublicAuthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/recover': {
      id: '/api/public/auth/recover'
      path: '/api/public/auth/recover'
      fullPath: '/api/public/auth/recover'
      preLoaderRoute: typeof ApiPublicAuthRecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/events/$id/sessions': {
      id: '/_authenticated/events/$id/sessions'
      path: '/$id/sessions'
      fullPath: '/events/$id/sessions'
      preLoaderRoute: typeof AuthenticatedEventsIdSessionsRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/events/$id/registrations': {
      id: '/_authenticated/events/$id/registrations'
      path: '/$id/registrations'
      fullPath: '/events/$id/registrations'
      preLoaderRoute: typeof AuthenticatedEventsIdRegistrationsRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/events/$id/edit': {
      id: '/_authenticated/events/$id/edit'
      path: '/$id/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof AuthenticatedEventsIdEditRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
  }
}

interface AuthenticatedEventsRouteChildren {
  AuthenticatedEventsNewRoute: typeof AuthenticatedEventsNewRoute
  AuthenticatedEventsIdEditRoute: typeof AuthenticatedEventsIdEditRoute
  AuthenticatedEventsIdRegistrationsRoute: typeof AuthenticatedEventsIdRegistrationsRoute
  AuthenticatedEventsIdSessionsRoute: typeof AuthenticatedEventsIdSessionsRoute
}

const AuthenticatedEventsRouteChildren: AuthenticatedEventsRouteChildren = {
  AuthenticatedEventsNewRoute: AuthenticatedEventsNewRoute,
  AuthenticatedEventsIdEditRoute: AuthenticatedEventsIdEditRoute,
  AuthenticatedEventsIdRegistrationsRoute:
    AuthenticatedEventsIdRegistrationsRoute,
  AuthenticatedEventsIdSessionsRoute: AuthenticatedEventsIdSessionsRoute,
}

const AuthenticatedEventsRouteWithChildren =
  AuthenticatedEventsRoute._addFileChildren(AuthenticatedEventsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedCheckinRoute: typeof AuthenticatedCheckinRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRouteWithChildren
  AuthenticatedParticipantsRoute: typeof AuthenticatedParticipantsRoute
  AuthenticatedPollsRoute: typeof AuthenticatedPollsRoute
  AuthenticatedSecurityAuditRoute: typeof AuthenticatedSecurityAuditRoute
  AuthenticatedAdminSetupRoute: typeof AuthenticatedAdminSetupRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedCheckinRoute: AuthenticatedCheckinRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRouteWithChildren,
  AuthenticatedParticipantsRoute: AuthenticatedParticipantsRoute,
  AuthenticatedPollsRoute: AuthenticatedPollsRoute,
  AuthenticatedSecurityAuditRoute: AuthenticatedSecurityAuditRoute,
  AuthenticatedAdminSetupRoute: AuthenticatedAdminSetupRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AgendaSlugRoute: AgendaSlugRoute,
  AnnoncesSlugRoute: AnnoncesSlugRoute,
  AttendanceSessionIdRoute: AttendanceSessionIdRoute,
  ESlugRoute: ESlugRoute,
  LiveSessionIdRoute: LiveSessionIdRoute,
  MatchmakingSlugRoute: MatchmakingSlugRoute,
  MeRoleRoute: MeRoleRoute,
  MessagesSlugRoute: MessagesSlugRoute,
  NetworkingSlugRoute: NetworkingSlugRoute,
  PollPollIdRoute: PollPollIdRoute,
  RdvSlugRoute: RdvSlugRoute,
  ApiPublicAuthRecoverRoute: ApiPublicAuthRecoverRoute,
  ApiPublicAuthTokenRoute: ApiPublicAuthTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
